{
 "title": "Host and NuCypher monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Network",
    "query": "label_values(ursula_host_info_info, domains)"
   },
   {
    "name": "app_version",
    "label": "App version",
    "query": "label_values(ursula_host_info_info, app_version)"
   }
  ]
 },
 "panels": [
  { "title": "NuCypher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current period",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ursula_current_period{instance=\"127.0.0.1:9101\"}"
    }
   ]
  },
  {
   "title": "Activity confirmed period",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ursula_activity_confirmed_period{instance=\"127.0.0.1:9101\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "NU staker balance",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ursula_staker_token_balance{instance=\"127.0.0.1:9101\"} / 10^18"
    }
   ]
  },
  {
   "title": "ETH staker balance",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ursula_staker_eth_balance{instance=\"127.0.0.1:9101\"}"
    }
   ]
  },
  {
   "title": "Owned tokens",
   "type": "singlestat",
   "description": "All tokens that belong to the staker, including locked, unlocked and rewards.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ursula_owned_tokens{instance=\"127.0.0.1:9101\"} / 10^18"
    }
   ]
  },
  {
   "title": "Unlocked tokens",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ursula_unlocked_tokens{instance=\"127.0.0.1:9101\"} / 10^18"
    }
   ]
  },
  {
   "title": "Restake status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ursula_restaking{instance=\"127.0.0.1:9101\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Winddown status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "ursula_wind_down{instance=\"127.0.0.1:9101\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Current ETH block",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ursula_current_eth_block_number{instance=\"127.0.0.1:9101\"}"
    }
   ]
  },
  {
   "title": "Worker set",
   "type": "graph",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "targets": [
    {
     "expr": "ursula_current_worker_is_me{instance=\"127.0.0.1:9101\"}",
     "legendFormat": "Worker"
    }
   ]
  },
  {
   "title": "Slashing",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ursula_last_slashed_penalty{instance=\"127.0.0.1:9101\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "ETH worker balance",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ursula_worker_eth_balance{instance=\"127.0.0.1:9101\"}"
    }
   ]
  },
  {
   "title": "Active stake",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ursula_active_stake{instance=\"127.0.0.1:9101\"} / 10^18"
    }
   ]
  },
  {
   "title": "Available refund",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ursula_available_refund{instance=\"127.0.0.1:9101\"} / 10^18"
    }
   ]
  },
  {
   "title": "Policy withdraw reward",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ursula_policy_withdrawn_reward{instance=\"127.0.0.1:9101\"} / 10^18"
    }
   ]
  },
  {
   "title": "Known nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ursula_known_nodes{instance=\"127.0.0.1:9101\"}"
    }
   ]
  },
  {
   "title": "Mined amount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Amount" }
   ],
   "targets": [
    {
     "expr": "ursula_mined_value{instance=\"127.0.0.1:9101\"}/10^18",
     "legendFormat": "Mined amount"
    }
   ]
  },
  {
   "title": "Work orders",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ursula_work_orders{instance=\"127.0.0.1:9101\"}",
     "legendFormat": "Work orders"
    }
   ]
  },
  {
   "title": "Policies held",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ursula_policies_held{instance=\"127.0.0.1:9101\"}",
     "legendFormat": "Policies held"
    }
   ]
  },
  {
   "title": "Missing confirmations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "ursula_missing_confirmations{instance=\"127.0.0.1:9101\"}",
     "legendFormat": "Missing confirmations"
    }
   ]
  },
  {
   "title": "Slashing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ursula_last_slashed_penalty{instance=\"127.0.0.1:9101\"}",
     "legendFormat": "Penalty value"
    }
   ]
  },
  {
   "title": "ETH balances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ursula_staker_eth_balance{instance=\"127.0.0.1:9101\"}",
     "legendFormat": "Staker ETH balance"
    },
    {
     "expr": "ursula_worker_eth_balance{instance=\"127.0.0.1:9101\"}",
     "legendFormat": "Worker ETH balance"
    }
   ]
  },
  {
   "title": "NU active stake amount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ursula_active_stake{instance=\"127.0.0.1:9101\"} / 10^18",
     "legendFormat": "NU amount"
    }
   ]
  },
  {
   "title": "Known nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ursula_known_nodes{instance=\"127.0.0.1:9101\"}",
     "legendFormat": "Nodes"
    }
   ]
  },
  {
   "title": "Worklock",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bid",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ursula_worklock_bid_depositedETH{instance=\"127.0.0.1:9101\"}/10^18",
       "legendFormat": "Bid ETH"
      }
     ]
    },
    {
     "title": "Claimed NU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "ursula_worklock_claimed_claimedTokens{instance=\"127.0.0.1:9101\"} / 10^18",
       "legendFormat": "Claimed NU"
      }
     ]
    },
    {
     "title": "Refunded ETH",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ursula_worklock_refund_refundETH{instance=\"127.0.0.1:9101\"}/10^18",
       "legendFormat": "Refunded ETH"
      }
     ]
    },
    {
     "title": "Work",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ursula_worklock_refund_completedWork{instance=\"127.0.0.1:9101\"}",
       "legendFormat": "Completed work"
      },
      {
       "expr": "ursula_worklock_refund_remaining_work{instance=\"127.0.0.1:9101\"}",
       "legendFormat": "Remaining work"
      }
     ]
    },
    {
     "title": "Deposited",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ursula_worklock_deposited_value{instance=\"127.0.0.1:9101\"}",
       "legendFormat": "Deposited"
      }
     ]
    }
   ]
  },
  {
   "title": "Ursula process info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "App version",
     "type": "text",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
     "content": "<center><h1>$app_version</h1></center>",
     "targets": [
      { "legendFormat": "Active stake" }
     ]
    },
    {
     "title": "Network",
     "type": "text",
     "gridPos": { "h": 3, "w": 3, "x": 10, "y": 3 },
     "content": "<center><h1>$network</h1></center>",
     "targets": [
      { "legendFormat": "Active stake" }
     ]
    },
    {
     "title": "Process uptime",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "time() - process_start_time_seconds{instance=\"127.0.0.1:9101\"}"
      }
     ]
    },
    {
     "title": "Ursula process CPU usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{instance=\"127.0.0.1:9101\"}[$__interval])",
       "legendFormat": "CPU usage"
      }
     ]
    },
    {
     "title": "Ursula process RAM usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{instance=\"127.0.0.1:9101\"}",
       "legendFormat": "Virtual memory"
      },
      {
       "expr": "process_resident_memory_bytes{instance=\"127.0.0.1:9101\"}",
       "legendFormat": "Resident memory"
      }
     ]
    },
    {
     "title": "Process opened file descriptors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{instance=\"127.0.0.1:9101\"}",
       "legendFormat": "Opened"
      },
      {
       "expr": "process_max_fds{instance=\"127.0.0.1:9101\"}",
       "legendFormat": "Max allowed"
      }
     ]
    }
   ]
  },
  {
   "title": "Quick CPU / Mem / Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Busy",
     "type": "gauge",
     "description": "Busy state of all CPU cores together",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "(((count(count(node_cpu_seconds_total{instance=~\"127.0.0.1:9100\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"127.0.0.1:9100\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"127.0.0.1:9100\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "Sys Load (5m avg)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together (5 min average)",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
     "targets": [
      {
       "expr": "avg(node_load5{instance=~\"127.0.0.1:9100\"}) /  count(count(node_cpu_seconds_total{instance=~\"127.0.0.1:9100\"}) by (cpu)) * 100"
      }
     ]
    },
    {
     "title": "Sys Load (15m avg)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together (15 min average)",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
     "targets": [
      {
       "expr": "avg(node_load15{instance=~\"127.0.0.1:9100\"}) /  count(count(node_cpu_seconds_total{instance=~\"127.0.0.1:9100\"}) by (cpu)) * 100"
      }
     ]
    },
    {
     "title": "RAM Used",
     "type": "gauge",
     "description": "Non available RAM memory",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
     "targets": [
      {
       "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"127.0.0.1:9100\"} * 100) / node_memory_MemTotal_bytes{instance=~\"127.0.0.1:9100\"})"
      }
     ]
    },
    {
     "title": "SWAP Used",
     "type": "gauge",
     "description": "Used Swap",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "((node_memory_SwapTotal_bytes{instance=~\"127.0.0.1:9100\"} - node_memory_SwapFree_bytes{instance=~\"127.0.0.1:9100\"}) / (node_memory_SwapTotal_bytes{instance=~\"127.0.0.1:9100\"} )) * 100"
      }
     ]
    },
    {
     "title": "Root FS Used",
     "type": "gauge",
     "description": "Used Root FS",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"127.0.0.1:9100\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"127.0.0.1:9100\",mountpoint=\"/\",fstype!=\"rootfs\"})"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "singlestat",
     "description": "Total number of CPU cores",
     "gridPos": { "h": 2, "w": 2, "x": 18, "y": 4 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{instance=~\"127.0.0.1:9100\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "RAM Total",
     "type": "singlestat",
     "description": "Total RAM",
     "gridPos": { "h": 2, "w": 2, "x": 20, "y": 4 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"127.0.0.1:9100\"}"
      }
     ]
    },
    {
     "title": "SWAP Total",
     "type": "singlestat",
     "description": "Total SWAP",
     "gridPos": { "h": 2, "w": 2, "x": 22, "y": 4 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "node_memory_SwapTotal_bytes{instance=~\"127.0.0.1:9100\"}"
      }
     ]
    },
    {
     "title": "Sys Load (1m avg)",
     "type": "singlestat",
     "description": "System Load (1m avg)",
     "gridPos": { "h": 2, "w": 2, "x": 18, "y": 6 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "node_load1{instance=~\"127.0.0.1:9100\"}"
      }
     ]
    },
    {
     "title": "RootFS Total",
     "type": "singlestat",
     "description": "Total RootFS",
     "gridPos": { "h": 2, "w": 2, "x": 20, "y": 6 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=~\"127.0.0.1:9100\",mountpoint=\"/\",fstype!=\"rootfs\"}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "singlestat",
     "description": "System uptime",
     "gridPos": { "h": 2, "w": 2, "x": 22, "y": 6 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "node_time_seconds{instance=~\"127.0.0.1:9100\"} - node_boot_time_seconds{instance=~\"127.0.0.1:9100\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Basic CPU / Mem / Net / Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Basic",
     "type": "graph",
     "description": "Basic CPU info",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"127.0.0.1:9100\"}[5m])) * 100",
       "legendFormat": "Busy System"
      },
      {
       "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=~\"127.0.0.1:9100\"}[5m])) * 100",
       "legendFormat": "Busy User"
      },
      {
       "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"127.0.0.1:9100\"}[5m])) * 100",
       "legendFormat": "Busy Iowait"
      },
      {
       "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"127.0.0.1:9100\"}[5m])) * 100",
       "legendFormat": "Busy IRQs"
      },
      {
       "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"127.0.0.1:9100\"}[5m])) * 100",
       "legendFormat": "Busy Other"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"127.0.0.1:9100\"}[5m])) * 100",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "Memory Basic",
     "type": "graph",
     "description": "Basic memory usage",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"127.0.0.1:9100\"}",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"127.0.0.1:9100\"} - node_memory_MemFree_bytes{instance=~\"127.0.0.1:9100\"} - (node_memory_Cached_bytes{instance=~\"127.0.0.1:9100\"} + node_memory_Buffers_bytes{instance=~\"127.0.0.1:9100\"})",
       "legendFormat": "RAM Used"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=~\"127.0.0.1:9100\"} + node_memory_Buffers_bytes{instance=~\"127.0.0.1:9100\"}",
       "legendFormat": "RAM Cache + Buffer"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=~\"127.0.0.1:9100\"}",
       "legendFormat": "RAM Free"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=~\"127.0.0.1:9100\"} - node_memory_SwapFree_bytes{instance=~\"127.0.0.1:9100\"})",
       "legendFormat": "SWAP Used"
      }
     ]
    },
    {
     "title": "Network Traffic Basic",
     "type": "graph",
     "description": "Basic network info per interface",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=~\"127.0.0.1:9100\",device=~\"(eth|enp).*\"}[5m])*8",
       "legendFormat": "recv {{device}}"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=~\"127.0.0.1:9100\",device=~\"(eth|enp).*\"}[5m])*8",
       "legendFormat": "trans {{device}} "
      }
     ]
    },
    {
     "title": "Disk Space Used Basic",
     "type": "graph",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"127.0.0.1:9100\",device!~'rootfs|lxcfs'} * 100) / node_filesystem_size_bytes{instance=~\"127.0.0.1:9100\",device!~'rootfs|lxcfs'})",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    }
   ]
  }
 ]
}